name = "AsciiDoc"
uuid = "8d64b9e2-4e3f-4a7d-9c8f-1e2d3f4a5b6c"
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]

[deps]
MarkdownAST = "d0879d2d-cac2-40c8-9cee-1863dc0c7391"

[compat]
MarkdownAST = "0.1.2"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
