[deps]
AsciiDocumenter = "8d64b9e2-4e3f-4a7d-9c8f-1e2d3f4a5b6c"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"

[sources]
AsciiDocumenter = {path = ".."}
